import {StyleSheet} from 'react-native';
import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';
import {Colors} from './colors';
import {FontsFmily} from './fonts';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    // alignItems: 'center',
  },
  semibldTxt: {
    fontSize: 16,
    fontFamily: FontsFmily.Semibold,
    color: Colors.black,
  },
  b0ldTxt: {
    fontSize: 14,
    fontFamily: FontsFmily.Semibold,
    color: Colors.black,
  },
  b0ldTxt2: {
    fontSize: 16,
    fontFamily: FontsFmily.Semibold,
    color: '#FFFFFF',
  },
  Txt2: {
    fontSize: 11,
    fontFamily: FontsFmily.Regular,
    color: Colors.MainColor,
    top: 2,
    width: 180,
  },
  startIcn: {
    width: wp(85),
    height: wp(85),
    marginTop: 75,
  },
  logwithBtn: {
    backgroundColor: '#FFFFFF',
    width: wp(85),
    height: 50,
    borderColor: Colors.MainColor,
    borderWidth: 1,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  error_view: {alignSelf: 'flex-start', alignSelf: 'center', top: 20},
  withbtnicn: {
    width: 20,
    height: 20,
  },
  ButtonMain: {
    width: wp(85),
    height: 50,
    backgroundColor: Colors.MainColor,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  ButonTxt: {
    fontSize: 16,
    fontFamily: FontsFmily.Semibold,
    color: '#FFFFFF',
  },
  flexHead: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: 10,
  },
  signavatr: {
    width: 85,
    height: 80,
    borderWidth: 1,
    borderColor: Colors.MainColor,
    borderRadius: 10,
    alignSelf: 'center',
    marginTop: 50,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avtarimg: {
    width: 80,
    height: 76,
    borderRadius: 10,
  },
  loginImg: {
    width: 188,
    height: 202,
    alignSelf: 'center',
    marginTop: 50,
  },
  outtxtinpt: {
    fontSize: 14,
    fontFamily: FontsFmily.Medium,
    color: '#000',
    paddingLeft: 5,
  },
  textinptBox: {
    width: wp(85),
    height: 50,
    backgroundColor: Colors.ligtgray,
    borderRadius: 8,
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 5,
    borderWidth: 0.5,
    borderColor: Colors.gray,
  },
  inputicon: {
    width: 15,
    height: 15,
    marginLeft: 12,
    tintColor: '#000000',
  },
  TextInputS: {
    color: Colors.black,
    paddingLeft: 10,
    fontSize: 14,
    fontFamily: FontsFmily.Regular,
    width: 250,
  },
  Iagreetxt: {
    fontSize: 13,
    fontFamily: FontsFmily.Medium,
    color: '#000000',
    paddingLeft: 10,
  },

  flexdirec: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checicn: {width: 17, height: 17},
  dotsimg: {
    width: wp(100),
    height: 110,
    marginTop: 40,
  },
  modalBackground: {
    flex: 1,
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(4, 4, 4,0.7)',
  },
  activityIndicatorWrapper: {
    backgroundColor: '#FFFFFF',
    paddingVertical: 10,
    width: wp(90),
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    // justifyContent: 'space-around',
  },
  MemIconimg: {
    width: 250,
    height: 250,
  },
  regulrtxt: {
    fontSize: 14,
    fontFamily: FontsFmily.Regular,
    color: Colors.black,
  },
  subscrimg: {
    width: wp(60),
    height: wp(60),
    alignSelf: 'center',
    marginTop: 40,
  },
  dollrimg: {
    width: 300,
    height: 70,
    alignSelf: 'center',
    marginTop: 40,
    // alignItems:'center',
    justifyContent: 'center',
  },
  dollrtxt: {
    fontSize: 14,
    fontFamily: FontsFmily.Semibold,
    color: '#FFFFFF',
  },
  dijitimg: {
    width: 300,
    height: 260,
    alignSelf: 'center',
    marginTop: 55,
  },
  cell: {
    width: 19,
    height: 20,
    lineHeight: 15,
    fontSize: 14,
    fontFamily: FontsFmily.Medium,
    borderBottomWidth: 1.5,
    borderColor: '#B880A5',
    textAlign: 'center',
    marginHorizontal: 8,
    color: 'red',
  },

  root: {
    // backgroundColor:'red'
  },
  codeFieldRoot: {
    marginTop: 8,
  },
  codeBox: {
    backgroundColor: '#FFFFFF',
    width: wp(80),
    height: 50,
    borderColor: '#CFCFCF',
    borderWidth: 1.5,
    borderRadius: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 50,
  },
  cardimg: {
    width: 200,
    height: 200,
    alignSelf: 'center',
  },
  textinptSmallBox: {
    width: wp(40),
    height: 50,
    backgroundColor: Colors.ligtgray,
    borderRadius: 8,
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 5,
  },
  outtxtinpt2: {
    fontSize: 14,
    fontFamily: FontsFmily.Medium,
    color: '#000',
    paddingLeft: 5,
  },
  TextInputS2: {
    color: Colors.black,
    paddingLeft: 15,
    fontSize: 12,
    fontFamily: FontsFmily.Medium,
    width: 120,
  },
  succsimg: {
    width: 200,
    height: 200,
  },
  bottomicon: {
    width: 20,
    height: 20,
  },
  mediumTxt: {
    fontSize: 16,
    fontFamily: FontsFmily.Medium,
    color: Colors.black,
  },
  forgotInputBox: {
    width: wp(85),
    height: 70,
    backgroundColor: Colors.ligtgray,
    borderRadius: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 1,
  },
  smsBox: {
    width: 50,
    height: 50,
    borderRadius: 10,
    backgroundColor: '#F7F7F7',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 1,
    borderWidth: 0.5,
    borderColor: '#CFCFCF',
    right: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  msgImg: {
    width: 25,
    height: 25,
  },
  pinView: {
    alignItems: 'center',
    alignSelf: 'center',
    width: wp(88),
    height: 70,
    marginTop: wp(15),
    // backgroundColor:'red',
  },
  cell2: {
    width: 70,
    height: 55,
    lineHeight: wp(16),
    fontSize: 20,
    fontFamily: FontsFmily.Medium,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E7E7E7',
    textAlign: 'center',
    marginHorizontal: 5,
    backgroundColor: '#FFFFFF',
    elevation: 0.5,
    color: '#000000',
  },
  focusCell: {
    // fontSize:29
  },
  root2: {
    flex: 1,
    padding: 20,
  },
  codeFieldRoot2: {},
  counter: {
    alignSelf: 'center',
    marginTop: wp(3),
    flexDirection: 'row',
    alignItems: 'center',
  },
  counter_txt: {
    color: '#000000',
    fontFamily: FontsFmily.Semibold,
    fontSize: 14,
  },
  HomeHeadr: {
    width: wp(100),
    height: 70,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    // borderBottomRightRadius: 30,
    // borderBottomLeftRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  homeHIcn: {
    width: 22,
    height: 22,
  },
  emtyimg: {
    width: 270,
    height: 270,
    alignSelf: 'center',
    marginTop: 150,
  },
  prfileimg: {
    width: 80,
    height: 80,
    borderRadius: 50,
    borderWidth: 0.7,
    borderColor: Colors.MainColor,
  },
  nameTxt_Inv: {
    color: '#000000',
    fontFamily: FontsFmily.Semibold,
    fontSize: 20,
  },
  nameTxt_Inv2: {
    color: '#000000',
    fontFamily: FontsFmily.Regular,
    fontSize: 14,
  },
  invite_flat: {
    width: 300,
    height: 70,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 2,
    borderRadius: 10,
    margin: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  invite_view1: {
    width: 250,
    height: 70,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'yellow',
  },
  invite_view2: {
    width: 25,
    height: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.MainColor,
    borderRadius: 15,
    right: 10,
  },
  invite_fltimg: {
    width: 40,
    height: 40,
    borderRadius: 25,
  },
  invite_flttxt: {
    color: '#666666',
    fontFamily: FontsFmily.Semibold,
    fontSize: 14,
  },
  inviteee: {
    width: 120,
    height: 50,
    backgroundColor: Colors.MainColor,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 2,
  },
  mediaSlct_box: {
    width: wp(85),
    height: 120,
    backgroundColor: Colors.ligtgray,
    borderRadius: 8,
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 5,
    borderWidth: 0.5,
    borderColor: Colors.gray,
  },
  mediaSlct_box2: {
    width: wp(85),
    height: 120,
    backgroundColor: Colors.ligtgray,
    borderRadius: 8,
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: 5,
    borderWidth: 0.5,
    borderColor: Colors.gray,
  },
  mediaSlct_imgs: {
    width: 60,
    height: 60,
  },
  mediaSlct_imgsplc: {
    width: 80,
    height: 80,
    borderRadius: 10,
  },
  Media_Dbox: {
    width: wp(85),
    height: 90,
    borderRadius: 8,
    borderColor: Colors.MainColor,
    borderWidth: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  media_imgB: {
    width: 80,
    height: 80,
  },
  photo_mediaF: {
    width: wp(85),
    height: 100,
    borderRadius: 8,
    borderColor: Colors.MainColor,
    borderWidth: 1,
    margin: 5,
    flexDirection: 'row',
  },
  flat_view1: {
    width: wp(25),
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
  },
  flat_view2: {
    width: wp(41),
    height: 100,
    justifyContent: 'space-evenly',
  },
  flat_view3: {
    width: wp(19),
    height: 95,
    justifyContent: 'space-around',
    alignItems: 'flex-end',
  },
  photo_Fimg: {
    width: wp(20),
    height: wp(20),
    borderRadius: 10,
  },
  photo_Ftxt1: {
    color: '#000000',
    fontFamily: FontsFmily.Semibold,
    fontSize: 14,
    paddingLeft: 7,
  },
  photo_Ftxt2: {
    color: '#2b2b2b',
    fontFamily: FontsFmily.Medium,
    fontSize: 10,
    paddingLeft: 7,
  },

  slide: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    // backgroundColor: '#f2f2f2',
  },
  slide2: {
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
    backgroundColor: '#f2f2f2',
    top: 41,
  },
  image: {
    width: wp(90),
    height: hp(37),
    borderRadius: 10,
  },
  readMore: {
    color: '#2b2b2b',
    fontFamily: FontsFmily.Regular,
    fontSize: 14,
    lineHeight: 25,
  },
  paginationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    // marginHorizontal:2,
    backgroundColor: Colors.MainColor,
  },
  videoBack: {
    backgroundColor: '#C83037',
    width: 22,
    height: 22,
    position: 'absolute',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    top: 5,
    left: 10,
  },
  DocBox: {
    width: wp(80),
    height: 100,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 2,
    borderRadius: 20,
    alignSelf: 'center',
    margin: 10,
  },
  curv_view2: {
    backgroundColor: '#D92835',
    borderTopLeftRadius: 35,
    borderBottomRightRadius: 20,
    width: 110,
    height: 40,
    // alignSelf: 'flex-end',
    alignItems: 'center',
    justifyContent: 'center',
  },
  curv_view1: {
    backgroundColor: '#D92835',
    borderTopLeftRadius: 20,
    borderBottomRightRadius: 35,
    width: 140,
    height: 50,
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  scrimg: {
    width: 55,
    height: 55,
    alignSelf: 'flex-end',
    right: 15,
  },
  doctxt: {
    color: '#8E8E8E',
    fontFamily: FontsFmily.Regular,
    fontSize: 12,
    lineHeight: 16,
    marginHorizontal: 5,
  },
  chatlist2: {
    width: wp(100),
    height: 70,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
  },

  chatlist: {
    width: wp(100),
    height: 70,
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    // borderBottomRightRadius: 30,
    // borderBottomLeftRadius: 30,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  card: {
    width: wp(100),
    height: 80,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
    borderTopColor: Colors.gray,
    borderBottomColor: Colors.gray,
    flexDirection: 'row',
  },
  card2: {
    width: wp(90),
    height: 60,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: Colors.MainColor,
    flexDirection: 'row',
    alignSelf: 'center',
    borderRadius: 10,
    margin: 2,
  },
  list_View1: {
    width: 80,
    height: 80,
    alignItems: 'center',
    justifyContent: 'center',
  },
  list_View2: {
    width: 180,
    height: 80,
  },
  list_View3: {
    width: 100,
    height: 80,
  },
  onlinedot: {
    width: 15,
    height: 15,
    borderRadius: 10,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    right: 10,
    bottom: 15,
  },
  ondot: {width: 12, height: 12, borderRadius: 6, backgroundColor: 'green'},
  leftView: {
    maxWidth: 150,
    minWidth: 100,
    height: 50,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 5,
    margin: 10,
  },
  rightView: {
    maxWidth: 200,
    minWidth: 100,
    height: 50,
    backgroundColor: '#FCCCCE',
    borderTopLeftRadius: 10,
    borderTopRightRadius: 10,
    borderBottomLeftRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,

    elevation: 3,
    margin: 10,
  },
  chatSendBox: {
    backgroundColor: '#FFFFFF',
    width: wp(85),
    height: 60,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexDirection: 'row',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,

    elevation: 1,
    borderWidth: 0.2,
    borderColor: Colors.gray,
    justifyContent: 'space-between',
  },
  sendarrow: {
    backgroundColor: Colors.MainColor,
    width: 45,
    height: 45,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    // right: 10,
  },
  sendarrow2: {
    backgroundColor: Colors.MainColor,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    right: 5,
  },
  options: {
    width: 160,
    height: 140,
    backgroundColor: '#FFFFFF',
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.18,
    shadowRadius: 1.0,

    elevation: 2,
    left: 25,
    bottom: 60,
    justifyContent: 'space-evenly',
  },
  OptionBackground: {
    flex: 1,
    // alignItems: 'center',
    justifyContent: 'flex-end',
    backgroundColor: 'transparent',
  },
  circle: {
    width: 35,
    height: 35,
    backgroundColor: '#E6E6E6',
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  Noticard: {
    width: wp(100),
    height: 100,
    backgroundColor: '#FFFFFF',
    borderTopWidth: 0.5,
    borderBottomWidth: 0.5,
    borderTopColor: Colors.gray,
    borderBottomColor: Colors.gray,
    flexDirection: 'row',
  },

  bell_View: {
    width: 60,
    height: 60,
    backgroundColor: '#FCCCCE',
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  eventDetails: {
    padding: 16,
    flex: 1,
    paddingBottom: 100,
  },
  selectedDateText: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  eventContainer: {
    padding: 10,
    marginBottom: 8,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  eventTitle: {
    color: '#000000',
    fontSize: 16,
    fontWeight: 'bold',
    paddingLeft: 10,
  },
  year: {
    color: '#000000',
    fontSize: 20,
    fontFamily: FontsFmily.Bold,
  },
  eventDescription: {
    color: '#350F50',
    fontSize: 11,
    fontFamily: FontsFmily.Regular,
  },
  tempStyle: {
    width: wp(95),
    height: 180,
    margin: 10,
    justifyContent: 'center',
  },
  cardimgB: {
    width: 75,
    height: 75,
    backgroundColor: '#E5DAB5',
    borderRadius: 10,
    // margin:13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardText1: {
    color: '#FFFFFF',
    fontSize: 18,
    fontFamily: FontsFmily.Semibold,
  },
  cardText2: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: FontsFmily.Medium,
  },
  cardText3: {
    color: '#FFFFFF',
    fontSize: 12,
    fontFamily: FontsFmily.Regular,
  },
  cardText4: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: FontsFmily.Semibold,
  },
  skip: {
    color: Colors.MainColor,
    fontSize: 14,
    fontFamily: FontsFmily.Semibold,
    right: 20,
  },
  buttonCentr: {
    flexDirection: 'row',
    alignItems: 'center',
    width: 180,
    justifyContent: 'space-between',
  },
  edit: {
    fontSize: 14,
    fontFamily: FontsFmily.Semibold,
    color: '#C83037',
  },
  chatTimeR: {
    fontSize: 12,
    fontFamily: FontsFmily.Medium,
    color: '#C1C1C1',
    paddingRight: 10,
    alignSelf: 'flex-end',
    bottom: 10,
  },
  chatTimeL: {
    fontSize: 12,
    fontFamily: FontsFmily.Medium,
    color: '#C1C1C1',
    paddingLeft: 10,
    bottom: 10,
  },
  ////////////////////////////////////////

  chatContainer: {
    paddingVertical: 16,
    paddingHorizontal: 12,
  },
  chatItem: {
    marginBottom: 12,
    maxWidth: '80%',
    padding: 8,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    minWidth: '20%',
    shadowColor: '#5A5252',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 1.5,
    alignSelf: 'flex-end',
    right: 10,
  },
  chatItemLft: {
    marginBottom: 12,
    maxWidth: '80%',
    minWidth: '20%',
    alignSelf: 'flex-start',
    padding: 8,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomRightRadius: 10,
    left: 10,
    shadowColor: '#5A5252',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 1.5,
  },
  sender: {
    fontSize: 14,
    fontFamily: FontsFmily.Regular,
    color: '#000',
  },
  message: {
    fontSize: 16,
  },
  imgBack: {
    width: 160,
    height: 210,
    backgroundColor: '#FFFFFF',
    marginBottom: 12,
    padding: 8,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomRightRadius: 10,
    left: 10,
    shadowColor: '#5A5252',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,

    elevation: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgBackR: {
    width: 160,
    height: 210,
    backgroundColor: '#FCCCCE',
    marginBottom: 12,
    padding: 8,
    borderTopRightRadius: 10,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    right: 10,
    shadowColor: '#5A5252',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    alignSelf: 'flex-end',
    elevation: 1.5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  textbox: {
    width: wp(70),
    paddingLeft: wp(4),
    paddingRight: wp(2),
    paddingVertical: hp(1),
    backgroundColor: 'red',
    borderRadius: wp(2),
    flexWrap: 'nowrap',
    marginBottom: hp(1),
  },
  msg: {
    fontSize: 14,
    fontFamily: 'MontserratAlternates-Regular',
  },
  tim: {
    alignSelf: 'flex-end',
    fontSize: 10,
    fontFamily: 'MontserratAlternates-Regular',
  },
  homeBtn: {
    width: '50%',
    backgroundColor: Colors.MainColor,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalBackground2: {
    flex: 1,
    alignItems: 'center',
    flexDirection: 'column',
    justifyContent: 'space-around',
    backgroundColor: 'rgba(4,4,4,0.6)',
  },
  modalBackgroundMain: {
    backgroundColor: '#fff',
    height: hp(60),
    width: wp(80),
    borderRadius: 10,
    shadowColor: '#5A5252',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
  },
  amount: {
    fontSize: 12,
    fontFamily: FontsFmily.Bold,
    color: '#000',
  },
  joinBtn: {
    width: wp(35),
    backgroundColor: Colors.MainColor,
    // borderRadius:5,
    alignItems: 'center',
    justifyContent: 'center',
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
    borderWidth: 1,
    borderColor: Colors.MainColor,
  },
  inviteBtn: {
    width: wp(35),

    alignItems: 'center',
    justifyContent: 'center',
    borderRightWidth: 1,
    borderBottomWidth: 1,
    borderTopWidth: 1,

    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
    borderColor: Colors.MainColor,
  },
  current: {
    fontSize: 14,
    fontFamily: FontsFmily.Regular,
    color: '#B4B4B4',
  },
  balance: {
    fontSize: 16,
    fontFamily: FontsFmily.Semibold,
    color: Colors.black,
  },
  line: {
    width: wp(95),
    height: 0.9,
    backgroundColor: '#B4B4B4',
  },
  withdralview: {
    width: wp(45),
    height: hp(10),
    backgroundColor: 'rgba(255,255,255,0.5)',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'space-evenly',
  },
  curView: {
    flex: 1,
    backgroundColor: '#fff',
    borderRadius: 15,
    marginTop: 30,
  },
  historyCart: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  dot: {
    width: 7,
    height: 7,
    backgroundColor: Colors.MainColor,
    borderRadius: 3.5,
    margin: 15,
  },
  inputGroup: {
    marginBottom: 20,
    backgroundColor: 'red',
  },
  label: {
    marginBottom: 5,
  },
  expiry: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  cvc: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
});
